# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RecognizedGesture.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RecognizedGesture.proto\"\xfb\x01\n\x07Gesture\x12,\n\x11recognizedGesture\x18\x01 \x01(\x0e\x32\x11.Gesture.Category\x12%\n\x0erecognizedHand\x18\x02 \x01(\x0e\x32\r.Gesture.Hand\"~\n\x08\x43\x61tegory\x12\x08\n\x04None\x10\x00\x12\x0f\n\x0b\x43losed_Fist\x10\x01\x12\r\n\tOpen_Palm\x10\x02\x12\x0f\n\x0bPointing_Up\x10\x03\x12\x0e\n\nThumb_Down\x10\x04\x12\x0c\n\x08Thumb_Up\x10\x05\x12\x0b\n\x07Victory\x10\x06\x12\x0c\n\x08ILoveYou\x10\x07\"\x1b\n\x04Hand\x12\x08\n\x04Left\x10\x00\x12\t\n\x05Right\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RecognizedGesture_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GESTURE']._serialized_start=28
  _globals['_GESTURE']._serialized_end=279
  _globals['_GESTURE_CATEGORY']._serialized_start=124
  _globals['_GESTURE_CATEGORY']._serialized_end=250
  _globals['_GESTURE_HAND']._serialized_start=252
  _globals['_GESTURE_HAND']._serialized_end=279
# @@protoc_insertion_point(module_scope)
